Saturn_BugTracker/Controllers/ApplicationUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Saturn_BugTracker.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Saturn_BugTracker.Controllers
{
    public class ApplicationUsersController : UniversalController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationUsers
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            List<ApplicationUser> users = db.Users.Where(user =>
            user.Email != "admin@bugtracker.com" &&
            user.Email != "project.manager@bugtracker.com" &&
            user.Email != "developer@bugtracker.com" &&
            user.Email != "submitter@bugtracker.com" &&
            user.Email != "nicholas.bonvan@gmail.com").ToList();
            
            return View(users);
        }

        // GET: ApplicationUsers/Details/5
        [Authorize(Roles = "Admin, Project Manager")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            UserRolesHelper userRolesHelper = new UserRolesHelper();
            List<IdentityRole> UserRoles = new List<IdentityRole>();

            ViewBag.UserRoles = userRolesHelper.UserRoles(id);
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        // GET: ApplicationUsers/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }

            List<string> otherRoles = new List<string>();
            List<string> currentRoles = new List<string>();
            UserRolesHelper userRolesHelper = new UserRolesHelper();
            foreach (IdentityUserRole r in applicationUser.Roles)
            {
                currentRoles.Add(userRolesHelper.FindRoleNameById(r.RoleId));
            }
            foreach(IdentityRole role in db.Roles)
            {
                if (!currentRoles.Contains(userRolesHelper.FindRoleNameById(role.Id))){
                    otherRoles.Add(role.Name);
                }
            }
            ViewBag.Roles = new MultiSelectList(otherRoles);
            ViewBag.CurrentRoles = new MultiSelectList(currentRoles);
            ViewBag.RolesCount = db.Roles.Count();

            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser, List<string> roles, List<string> CurrentRoles)
        {
            //ViewBag.Roles = new MultiSelectList(db.Roles, "Id", "Name");
            
            if (ModelState.IsValid)
            {
                UserRolesHelper userRolesHelper = new UserRolesHelper();
                if(CurrentRoles != null)
                {
                    foreach (string role in CurrentRoles)
                    {
                        userRolesHelper.RemoveUserFromRole(applicationUser.Id, role);
                    }
                }
                
                if(roles != null)
                {
                    foreach (string role in roles)
                    {
                        string userId = applicationUser.Id;
                        userRolesHelper.AddUserToRole(userId, role);
                    }
                }
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = applicationUser.Id });
            }
            return RedirectToAction("Index");
        }

        // GET: ApplicationUsers/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Saturn_BugTracker/Views/ApplicationUsers/Delete.cshtml
@model Saturn_BugTracker.Models.ApplicationUser

<!-- START PAGE HEADING -->
<div class="app-heading app-heading-bordered app-heading-page">
    <div class="icon icon-lg">
        <span class="icon-laptop-phone"></span>
    </div>
    <div class="title">
        <h1>Saturn Manager</h1>
        <p>Welcome!</p>
    </div>
    <!--
    <div class="heading-elements">
        <a href="#" class="btn btn-danger" id="page-like"><span class="app-spinner loading"></span> loading...</a>
        <a href="https://themeforest.net/item/boooya-revolution-admin-template/17227946?ref=aqvatarius&license=regular&open_purchase_for_item_id=17227946" class="btn btn-success btn-icon-fixed"><span class="icon-text">$24</span> Purchase</a>
    </div>
    -->
</div>
<div class="app-heading-container app-heading-bordered bottom">
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")">Application</a></li>
        <li><a href="@Url.Action("Index", "ApplicationUsers")">User Management</a></li>
        <li class="active">Delete User</li>
    </ul>
</div>
<!-- END PAGE HEADING -->

<!-- START CONTAINER -->
<div class="container">
    <!-- START ROW -->
    <div class="row">
        <!-- START COL-->
        <div class="col-md-8 col-md-offset-2">
            <!-- START BLOCK -->
            <div class="block">
                <!-- START BLOCK CONTENT -->
                <div class="block-content">

                    <h2 style="text-align:center">Delete User</h2>
                    <hr />
                    <hr />

                    <table class="table-striped table-bordered table datatable-extended">
                        <tbody>
                            <tr>
                                <td>First Name</td>
                                <td>@Html.DisplayFor(model => model.FirstName)</td>
                            </tr>
                            <tr>
                                <td>Last Name</td>
                                <td>@Html.DisplayFor(model => model.LastName)</td>
                            </tr>
                            <tr>
                                <td>Display Name</td>
                                <td>@Html.DisplayFor(model => model.DisplayName)</td>
                            </tr>
                            <tr>
                                <td>User Name</td>
                                <td>@Html.DisplayFor(model => model.UserName)</td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>@Html.DisplayFor(model => model.Email)</td>
                            </tr>
                            <tr>
                                <td>Email Confirmed</td>
                                <td>@Html.DisplayFor(model => model.EmailConfirmed)</td>
                            </tr>
                            <tr>
                                <td>Phone Number</td>
                                <td>@Html.DisplayFor(model => model.PhoneNumber)</td>
                            </tr>
                            <tr>
                                <td>Phone Number Confirmed</td>
                                <td>@Html.DisplayFor(model => model.PhoneNumberConfirmed)</td>
                            </tr>
                            <tr>
                                <td>Two Factor Authentication Enabled</td>
                                <td>@Html.DisplayFor(model => model.TwoFactorEnabled)</td>
                            </tr>
                            <tr>
                                <td>Lockout End Date</td>
                                <td>@Html.DisplayFor(model => model.LockoutEndDateUtc)</td>
                            </tr>
                            <tr>
                                <td>Lockout Enabled</td>
                                <td>@Html.DisplayFor(model => model.LockoutEnabled)</td>
                            </tr>
                            <tr>
                                <td>Access Failed Count</td>
                                <td>@Html.DisplayFor(model => model.AccessFailedCount)</td>
                            </tr>
                        </tbody>
                    </table>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div style="text-align:center">
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            @Html.ActionLink("Return", "Index", null, htmlAttributes: new { @class = "btn btn-primary" })
                        </div>
                    }
                </div>
                <!-- END BLOCK CONTENT -->
            </div>
            <!-- END BLOCK -->
        </div>
        <!-- END COL-->
    </div>
    <!-- END ROW -->
</div>
<!-- END CONTAINER -->

Saturn_BugTracker/Views/ApplicationUsers/Details.cshtml
@model Saturn_BugTracker.Models.ApplicationUser

<!-- START PAGE HEADING -->
<div class="app-heading app-heading-bordered app-heading-page">
    <div class="icon icon-lg">
        <span class="icon-laptop-phone"></span>
    </div>
    <div class="title">
        <h1>Saturn Manager</h1>
        <p>Welcome!</p>
    </div>
    <!--
    <div class="heading-elements">
        <a href="#" class="btn btn-danger" id="page-like"><span class="app-spinner loading"></span> loading...</a>
        <a href="https://themeforest.net/item/boooya-revolution-admin-template/17227946?ref=aqvatarius&license=regular&open_purchase_for_item_id=17227946" class="btn btn-success btn-icon-fixed"><span class="icon-text">$24</span> Purchase</a>
    </div>
    -->
</div>
<div class="app-heading-container app-heading-bordered bottom">
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")">Application</a></li>
        <li><a href="@Url.Action("Index", "ApplicationUsers")">User Management</a></li>
        <li class="active">User Details</li>
    </ul>
</div>
<!-- END PAGE HEADING -->

<!-- START CONTAINER -->
<div class="container">
    <!-- START ROW -->
    <div class="row">
        <!-- START COL-->
        <div class="col-md-8 col-md-offset-2">
            <!-- START BLOCK -->
            <div class="block">
                <!-- START BLOCK CONTENT -->
                <div class="block-content">
                    <h2 style="text-align:center">User Details</h2>
                    <div>
                        <hr />
                        <hr />
                        <!-- START TABLE -->
                        <table class="table table-striped table-bordered">
                            <!-- START TABLE BODY -->
                            <tbody>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.FirstName)</td>
                                    <td>@Html.DisplayFor(model => model.FirstName)</td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.LastName)</td>
                                    <td>@Html.DisplayFor(model => model.LastName)</td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.DisplayName)                   </td>
                                    <td>@Html.DisplayFor(model => model.DisplayName)                       </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.UserName)                      </td>
                                    <td>@Html.DisplayFor(model => model.UserName)                          </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.Email)                         </td>
                                    <td>@Html.DisplayFor(model => model.Email)                             </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.EmailConfirmed)                </td>
                                    <td>@Html.DisplayFor(model => model.EmailConfirmed)                    </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.PhoneNumber)                   </td>
                                    <td>@Html.DisplayFor(model => model.PhoneNumber)                       </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.PhoneNumberConfirmed)          </td>
                                    <td>@Html.DisplayFor(model => model.PhoneNumberConfirmed)              </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.TwoFactorEnabled)              </td>
                                    <td>@Html.DisplayFor(model => model.TwoFactorEnabled)                  </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.LockoutEndDateUtc)             </td>
                                    <td>@Html.DisplayFor(model => model.LockoutEndDateUtc)                 </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.LockoutEnabled)                </td>
                                    <td>@Html.DisplayFor(model => model.LockoutEnabled)                    </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.AccessFailedCount)             </td>
                                    <td>@Html.DisplayFor(model => model.AccessFailedCount)                 </td>
                                </tr>
                                <tr>
                                    <td>@Html.DisplayNameFor(model => model.Roles)</td>
                                    <td>
                                        @foreach (string role in ViewBag.UserRoles)
                                        {
                                            @Html.Raw(role)
                                            <br />
                                        }
                                    </td>
                                </tr>
                            </tbody>

                            <!-- END TABLE BODY -->
                        </table>
                        <!-- END TABLE -->
                    </div>
                    <p style="text-align:center">
                        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
                        <a class="btn btn-primary" href="@Url.Action("Index", "ApplicationUsers")">Return</a>
                    </p>
                </div>
                <!-- END BLOCK CONTENT -->
            </div>
            <!-- END BLOCK -->
        </div>
        <!-- END COL-->
    </div>
    <!-- END ROW -->
</div>
<!-- END CONTAINER -->

Saturn_BugTracker/Views/ApplicationUsers/Edit.cshtml
@model Saturn_BugTracker.Models.ApplicationUser

@using Microsoft.AspNet.Identity;
@using Microsoft.AspNet.Identity.EntityFramework;

@{
    MultiSelectList roles = new MultiSelectList(ViewBag.Roles);
    MultiSelectList currentRoles = new MultiSelectList(ViewBag.CurrentRoles);
}

<!-- START PAGE HEADING -->
<div class="app-heading app-heading-bordered app-heading-page">
    <div class="icon icon-lg">
        <span class="icon-laptop-phone"></span>
    </div>
    <div class="title">
        <h1>Saturn Manager</h1>
        <p>Welcome!</p>
    </div>
    <!--
    <div class="heading-elements">
        <a href="#" class="btn btn-danger" id="page-like"><span class="app-spinner loading"></span> loading...</a>
        <a href="https://themeforest.net/item/boooya-revolution-admin-template/17227946?ref=aqvatarius&license=regular&open_purchase_for_item_id=17227946" class="btn btn-success btn-icon-fixed"><span class="icon-text">$24</span> Purchase</a>
    </div>
    -->
</div>
<div class="app-heading-container app-heading-bordered bottom">
    <ul class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")">Application</a></li>
        <li><a href="@Url.Action("Index", "ApplicationUsers")">User Management</a></li>
        <li class="active">User Edit</li>
    </ul>
</div>
<!-- END PAGE HEADING -->

<!-- START CONTAINER -->
<div class="container">
    <!-- START ROW -->
    <div class="row">
        <!-- START COL-->
        <div class="col-md-8 col-md-offset-2">
            <!-- START BLOCK -->
            <div class="block">
                <!-- START BLOCK CONTENT -->
                <div class="block-content">
                    <h1 style="text-align:center">Edit User</h1>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.PasswordHash)
                        @Html.HiddenFor(model => model.SecurityStamp)

                        <table class="table table-striped table-bordered">
                            <tr>
                                <td>First Name</td>
                                <td>
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Last Name</td>
                                <td>
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Display Name</td>
                                <td>
                                    @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>User Name</td>
                                <td>
                                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Email Confirmed</td>
                                <td>
                                    @Html.EditorFor(model => model.EmailConfirmed)
                                    @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Phone Number</td>
                                <td>
                                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Phone Number Confirmed</td>
                                <td>
                                    @Html.EditorFor(model => model.PhoneNumberConfirmed)
                                    @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Two Factor Authentication Enabled</td>
                                <td>
                                    @Html.EditorFor(model => model.TwoFactorEnabled)
                                    @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Lockout End Date</td>
                                <td>
                                    @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Lockout Enabled</td>
                                <td>
                                    @Html.EditorFor(model => model.LockoutEnabled)
                                    @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                <td>Access Failed Count</td>
                                <td>
                                    @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
                                </td>
                            </tr>
                            <tr>
                                @if (currentRoles.Count() == ViewBag.RolesCount || ViewBag.Roles == null)
                                {
                                    <td>Add To Roles</td>
                                    <td><strong>User is assigned to all roles</strong></td>
                                }
                                else
                                {
                                    <td>Add to Roles</td>
                                    <td>@Html.ListBox("Roles", (MultiSelectList)ViewBag.Roles, new { htmlAttributes = new { @class = "form-control" } })</td>
                                }
                            </tr>
                            <tr>
                                @if (ViewBag.CurrentRoles == null || currentRoles.Count() == 0)
                                {
                                    <td>Remove From Roles</td>
                                    <td><strong>No Roles Assigned</strong></td>
                                }
                                else
                                {
                                    <td>Remove From Roles</td>
                                    <td>@Html.ListBox("CurrentRoles", null, new { htmlAttributes = new { @class = "form-control" } })</td>
                                }
                            </tr>
                        </table>

                        <div class="form-group">
                            <div style="text-align:center">
                                <input type="submit" value="Save" class="btn btn-success" />
                                @Html.ActionLink("Return", "Index", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    }
                </div>
                <!-- END BLOCK CONTENT -->
            </div>
            <!-- END BLOCK -->
        </div>
        <!-- END COL-->
    </div>
    <!-- END ROW -->
</div>
<!-- END CONTAINER -->